-- Lumina Studio backend schema (Supabase/Postgres)

-- Extensions
create extension if not exists pgcrypto;

-- Updated-at trigger helper
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Admin users (who can manage content in Studio Control / Admin UI)
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.admin_users au
    where au.user_id = auth.uid()
  );
$$;

create policy "Admin can read admin_users"
on public.admin_users
for select
to authenticated
using (public.is_admin());

create policy "Admin can manage admin_users"
on public.admin_users
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Portfolio
create table if not exists public.collections (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  title text not null,
  category text not null,
  image_url text not null,
  description text,
  is_featured boolean not null default false,
  display_order integer not null default 0
);

create table if not exists public.groups (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  collection_id integer not null references public.collections(id) on delete cascade,
  title text not null,
  description text not null,
  date_text text not null,
  location text not null,
  display_order integer not null default 0
);

do $$
begin
  if not exists (
    select 1 from pg_type where typname = 'image_orientation'
  ) then
    create type public.image_orientation as enum ('portrait', 'landscape');
  end if;
end $$;

create table if not exists public.images (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  group_id integer not null references public.groups(id) on delete cascade,
  url text not null,
  caption text,
  orientation public.image_orientation,
  display_order integer not null default 0,
  is_preview boolean not null default false,
  preview_order integer
);

create index if not exists idx_groups_collection_id on public.groups(collection_id);
create index if not exists idx_images_group_id on public.images(group_id);
create index if not exists idx_images_group_preview on public.images(group_id, is_preview, preview_order);

-- Testimonials
create table if not exists public.testimonials (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  role text not null,
  quote text not null,
  image text not null,
  rating integer not null default 5,
  display_order integer not null default 0
);

-- Pricing (features stored inline for simplicity)
create table if not exists public.pricing_tiers (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  price text not null,
  features text[] not null default '{}',
  recommended boolean not null default false,
  display_order integer not null default 0
);

-- Enquiries (public write, admin read)
create table if not exists public.enquiries (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  event_date date,
  event_type text not null,
  guests text,
  style text,
  message text not null
);

-- Triggers
drop trigger if exists trg_collections_updated_at on public.collections;
create trigger trg_collections_updated_at
before update on public.collections
for each row execute function public.set_updated_at();

drop trigger if exists trg_groups_updated_at on public.groups;
create trigger trg_groups_updated_at
before update on public.groups
for each row execute function public.set_updated_at();

drop trigger if exists trg_images_updated_at on public.images;
create trigger trg_images_updated_at
before update on public.images
for each row execute function public.set_updated_at();

drop trigger if exists trg_testimonials_updated_at on public.testimonials;
create trigger trg_testimonials_updated_at
before update on public.testimonials
for each row execute function public.set_updated_at();

drop trigger if exists trg_pricing_tiers_updated_at on public.pricing_tiers;
create trigger trg_pricing_tiers_updated_at
before update on public.pricing_tiers
for each row execute function public.set_updated_at();

-- RLS
alter table public.collections enable row level security;
alter table public.groups enable row level security;
alter table public.images enable row level security;
alter table public.testimonials enable row level security;
alter table public.pricing_tiers enable row level security;
alter table public.enquiries enable row level security;

-- Public read policies
create policy "Public can read collections"
on public.collections for select
to anon, authenticated
using (true);

create policy "Public can read groups"
on public.groups for select
to anon, authenticated
using (true);

create policy "Public can read images"
on public.images for select
to anon, authenticated
using (true);

create policy "Public can read testimonials"
on public.testimonials for select
to anon, authenticated
using (true);

create policy "Public can read pricing tiers"
on public.pricing_tiers for select
to anon, authenticated
using (true);

-- Enquiries: public insert
create policy "Public can create enquiry"
on public.enquiries for insert
to anon, authenticated
with check (true);

-- Enquiries: admin read
create policy "Admin can read enquiries"
on public.enquiries for select
to authenticated
using (public.is_admin());

-- Admin write policies (content management)
create policy "Admin can manage collections"
on public.collections for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admin can manage groups"
on public.groups for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admin can manage images"
on public.images for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admin can manage testimonials"
on public.testimonials for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admin can manage pricing tiers"
on public.pricing_tiers for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

